CREATE SEQUENCE FREEBOARD_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE TABLE FREEBOARD(
    BNO NUMBER(10,0) DEFAULT FREEBOARD_SEQ.NEXTVAL NOT NULL,
    TITLE VARCHAR2(300) DEFAULT '제목' NOT NULL,
    WRITER VARCHAR2(50) DEFAULT '글쓴이' NOT NULL,
    CONTENT VARCHAR2(2000) DEFAULT '내용' NOT NULL,
    REGDATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATEDATE DATE DEFAULT SYSDATE NOT NULL
);
ALTER TABLE FREEBOARD ADD CONSTRAINT FREEBOARD_PK PRIMARY KEY (BNO);